#!/usr/bin/env python

import serial
import picamera
import sys, os, subprocess
import requests, json
import time, datetime

from run_inference import generateCaption

SERVER_URL = 'http://ec2-18-191-1-128.us-east-2.compute.amazonaws.com:8080/'
UPLOAD_IMAGE_URI = 'images'
PHOTOFORMAT = 'jpeg'

def takePicture(filename):
  with picamera.PiCamera() as camera:
    camera.resolution = (1920, 1080)
    camera.capture(filename + '.' + PHOTOFORMAT, format=PHOTOFORMAT)
    print("Photo captured and saved ...")
    return filename + '.' + PHOTOFORMAT

def timestamp():
  tstring = datetime.datetime.now()
  print("Filename generated ...")
  return tstring.strftime("%Y%m%d_%H%M%S")

def deleteFile(filename):
  os.system("rm " + filename + '.' + PHOTOFORMAT)
  print("File: " + filename + " deleted ...")

def uploadPicture(filename, caption, coords):
  filePath = './' + filename + '.' + PHOTOFORMAT

  with open(filePath, 'rb') as f:
    print("Uploading " + filename + " to AWS Server")
    
    headers = {'caption': caption, 'coordinates': coords} 
    files = {'file': f}
    url = SERVER_URL + UPLOAD_IMAGE_URI 

    try: 
      r = requests.post(url, files=files, headers=headers)
      print(r.status_code)
      r.raise_for_status()
    except Exception as e:
      print("ERROR: File upload failed")
    else:
      print("File upload succeeded!")

def getLocation():
  send_url = 'http://freegeoip.net/json'
  r = requests.get(send_url)
  j = json.loads(r.text)
  lat = j['latitude']
  lon = j['longitude']
  return str(lat) + ',' + str(lon)

def main():
  serialData = serial.Serial('/dev/ttyACM0',115200) 
  while True: 
    input = serialData.read()
    while(input != 'P'):
      input = serialData.read()
    serialData.write(b'p')

    input = serialData.read()
    while(input != 'G'):
      input = serialData.read()

    serialData.write(b'g')
    
    while(serialData.in_waiting == 0):
      continue; 
    longitude = ''
    input = serialData.read()
    
    while(input =! '\n'):
      longitude = longitude + str(input)
      input = serialData.read()  
 
    while(serialData.in_waiting == 0):
      continue;
    latitude = ''
    input = serialDataread()
    
    while(input != '\n')
      latitude = longitude + input
      input = serialData.read()

    #Generate filename from current time
    filename = timestamp()

    #Capture photo
    file = takePicture(filename)

    #Generate Caption
    caption = generateCaption("./" + filename + "." + PHOTOFORMAT)
    #coords = getLocation()
    coords = latitude + ',' + longitude 

    subprocess.call("../speech.sh "+caption, shell=True)
    print("Generated caption for photo is: " + caption)
    #Upload photo
    uploadPicture(filename, caption, coords)

    #Delete local file
    deleteFile(filename)

    print("Done\n\n")

if __name__ == '__main__':
  main() 
